package com.orasi.utils.database.sqlStorage;

public class ReservationInfo {
	public String findVacantRoomByRoomTypeCode(String roomTypeCd, String locationId){
		return "SELECT RM.RSRC_ID, RM.RM_NM "+
				"FROM RSRC_INV.WRK_LOC "+
				"JOIN RSRC_INV.RM ON RSRC_INV.WRK_LOC.HM_RSRT_FAC_ID = RSRC_INV.RM.RSRT_FAC_ID "+
				"JOIN RSRC_INV.RSRC_INVTRY_TYP TYPE ON RSRC_INV.RM.RSRC_INVTRY_TYP_ID = TYPE.RSRC_INVTRY_TYP_ID "+
				"JOIN RSRC_INV.RSRC_STS ON RM.RSRC_ID= RSRC_STS.RSRC_ID "+
				"JOIN RSRC_INV.RSRC_INVTRY_STS ON RSRC_STS.RSRC_INVTRY_STS_ID = RSRC_INVTRY_STS.RSRC_INVTRY_STS_ID "+
				"JOIN HOUSKEEPNG.DLY_RM_STS ON HOUSKEEPNG.DLY_RM_STS.RM_ID_VL = RSRC_INV.RM.RM_ID_VL "+
				"JOIN HOUSKEEPNG.RM_HSKP_STS ON HOUSKEEPNG.DLY_RM_STS.RM_STS_ID = HOUSKEEPNG.RM_HSKP_STS.RM_STS_ID "+
				"JOIN HOUSKEEPNG.RM_OCPNCY_STS ON HOUSKEEPNG.RM_HSKP_STS.RM_STS_ID = HOUSKEEPNG.RM_OCPNCY_STS.RM_STS_ID "+
				"JOIN RSRC_INV.RSRC ON RM.RSRC_ID= RSRC.RSRC_ID "+
				"WHERE RSRC_INVTRY_STS.RSRC_INVTRY_STS_ID IN (15) "+
				"AND RSRC_INVTRY_STS.RSRC_INVTRY_STS_ID NOT IN (4,5,6,7,8) "+
				"AND TXN_ACCT_CTR_ID Is Not NULL "+
				"AND TXN_ACCT_CTR_ID NOT IN(7047, 11775) "+ 
				"AND WRK_LOC_NM Not Like '%HP_ServiceTest%' "+
				"AND  RSRC_INVTRY_TYP_CD = '" + roomTypeCd + "' "+				
				"AND RSRC_INV.WRK_LOC.WRK_LOC_ID = "+ locationId +" "+
				"AND RSRC_INV.RSRC_INVTRY_STS.STS_NM = 'VACANT' "+
				"AND HOUSKEEPNG.RM_HSKP_STS.STS_NM = 'CLEAN' "+
				"AND RSRC.ASGN_OWNR_ID IS NULL "+
				"AND ROWNUM = 1";
	}
	
}
